name: Autograding Tests
'on':
  - push
  - workflow_dispatch
  - repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Java 21
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '21'
      - name: Lab3 Autograde Test
        id: lab3-autograde-test
        uses: education/autograding-command-grader@v1
        with:
          test-name: Lab3 Autograde Test
          setup-command: for file in __autograde__/*; do cp "$file" "src/$(basename
            "$file").java"; done; javac -cp 'lib/*:src' src/* -d out;
          command: java -cp "out/:lib/*" org.junit.platform.console.ConsoleLauncher
            --select-class AutoGradeTests
          timeout: 1
      - name: Autograding Reporter
        uses: education/autograding-grading-reporter@v1
        env:
          LAB3-AUTOGRADE-TEST_RESULTS: "${{steps.lab3-autograde-test.outputs.result}}"
        with:
          runners: lab3-autograde-test